# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'
strategy:
  matrix:
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    pwd
    ls -la
  displayName: 'Verify build environment (pre)'

- script: |
    make install
  displayName: 'Install dependencies'

- script: |
    make test
  displayName: 'Test project'

- script: |
    make package
  displayName: 'Package project'

- script: |
    pwd
    ls -la
  displayName: 'Verify build environment (post)'